- name: Create a Docker container with function app
  hosts: localhost
  connection: local
  vars_files:
   - ./vars-myvars.yml
  vars:
    registry_name: "{{ function_name }}{{ rnum }}acr"
    task_name: buildtask
  tasks:

    - name: Create container registry
      azure_rm_containerregistry:
        resource_group: "{{ resource_group }}"
        name: "{{ registry_name }}"
        location: eastus
        admin_user_enabled: true
        sku: Premium
           
    - name: Build Image using Azure Container Registry
      azure_rm_resource:
        api_version: '2018-09-01'
        resource_group: "{{ resource_group }}"
        provider: containerregistry
        resource_type: registries
        resource_name: "{{ registry_name }}"
        subresource:
          - type: tasks
            name: "{{ task_name }}"
        body:
          properties: 
            status: Enabled
            platform: 
              os: Linux
              architecture: amd64
            agentConfiguration: 
              cpu: 2
            step: 
              type: Docker
              imageNames: 
                - functionapp
              dockerFilePath: Dockerfile
              contextPath: function-app-container
              isPushEnabled: true
              noCache: false
            trigger: 
              sourceTriggers: 
                - name: mySourceTrigger
                  sourceRepository: 
                    sourceControlType: Github
                    repositoryUrl: https://github.com/{{ github_id }}/RedHatSummit2019
                    branch: master
                    sourceControlAuthProperties: 
                      tokenType: PAT
                      token:  "{{ github_token }}"
                  sourceTriggerEvents: 
                    - commit
              baseImageTrigger: 
                name: myBaseImageTrigger
                baseImageTriggerType: Runtime
          location: eastus
