- name: Create function app with Ansible in Docker container
  hosts: localhost
  connection: local
  vars_files:
   - ./vars-myvars.yml
  vars:
    storage_name: "{{ function_name }}{{ rnum }}st"
  tasks:
    - name: Create a linux app service plan
      azure_rm_appserviceplan:
        resource_group: "{{ resource_group }}"
        name: "{{ function_app }}plan"
        sku: S1
        is_linux: true
        number_of_workers: 1

    - name: create storage account for function apps
      azure_rm_storageaccount:
        resource_group: '{{ resource_group }}'
        name: "{{ storage_name }}"
        account_type: Standard_LRS
        kind: StorageV2

    - name: Obtain storage keys
      azure_rm_resource:
        api_version: '2018-07-01'
        method: POST
        resource_group: "{{ resource_group }}"
        provider: storage
        resource_type: storageaccounts
        resource_name: "{{ storage_name }}"
        subresource:
          - type: listkeys
      register: storage_output

    - name: Create container based function app
      azure_rm_functionapp:
        resource_group: "{{ resource_group }}"
        name: "{{ function_name }}"
        storage_account: "{{ storage_name }}"
        plan:
          resource_group: "{{ resource_group }}"
          name: "{{ function_name }}plan"
        container_settings:
          name: zikalino/functionapp:x7
        app_settings:
          AzureWebJobsStorage: DefaultEndpointsProtocol=https;AccountName={{ function_app_name }}stx;AccountKey={{ storage_output['response']['keys'][0]['value'] }}
          DOCKER_REGISTRY_SERVER_URL: https://index.docker.io
          WEBSITE_NODE_DEFAULT_VERSION: 10.14.1
          WEBSITES_ENABLE_APP_SERVICE_STORAGE: no
