- name: Create function app with Ansible in Docker container
  hosts: localhost
  connection: local
  # vars_files:
  #  - ./vars-myvars.yml

  vars:
    resource_group: zimswebapp
    function_app_name: zimsffunctionacr
    registry_name: zimscontainerregistry
  tasks:
    - name: Create a linux app service plan
      azure_rm_appserviceplan:
        resource_group: "{{ resource_group }}"
        name: "{{ function_app_name }}plan"
        sku: S1
        is_linux: true
        number_of_workers: 1

    - name: create storage account for function apps
      azure_rm_storageaccount:
        resource_group: '{{ resource_group }}'
        name: "{{ function_app_name }}stx"
        account_type: Standard_LRS
      register: output

    - name: Obtain storage keys
      azure_rm_resource:
        api_version: '2018-07-01'
        method: POST
        resource_group: "{{ resource_group }}"
        provider: storage
        resource_type: storageaccounts
        resource_name: "{{ function_app_name }}stx"
        subresource:
          - type: listkeys
      register: storage_output

    - name: Obtain Azure Container Registry Facts
      azure_rm_containerregistry_facts:
        resource_group: "{{ resource_group }}"
        name: "{{ registry_name }}"
        retrieve_credentials: true
      register: acr_output

    - name: Create container based function app
      azure_rm_functionapp:
        resource_group: "{{ resource_group }}"
        name: "{{ function_app_name }}"
        storage_account: "{{ function_app_name }}stx"
        plan:
          resource_group: "{{ resource_group }}"
          name: "{{ function_app_name }}plan"
        container_settings:
          name: functionapp
          registry_server_url: "{{ acr_output.registries[0].login_server }}"
          registry_server_user: "{{ acr_output.registries[0].name }}"
          registry_server_password: "{{ acr_output.registries[0].credentials.password }}"
        app_settings:
          AzureWebJobsStorage: DefaultEndpointsProtocol=https;AccountName={{ function_app_name }}stx;AccountKey={{ storage_output['response']['keys'][0]['value'] }}
          WEBSITE_NODE_DEFAULT_VERSION: 10.14.1
          WEBSITES_ENABLE_APP_SERVICE_STORAGE: no
