- name: Create function app with Ansible in Docker container
  hosts: localhost
  connection: local
   vars_files:
    - ./vars-myvars.yml

  tasks:
    - name: Create a linux app service plan
      azure_rm_appserviceplan:
        resource_group: "{{ resource_group }}"
        name: "{{ function_app_name }}plan"
        sku: S1
        is_linux: true
        number_of_workers: 1

    - name: create storage account for function apps
      azure_rm_storageaccount:
        resource_group: '{{ resource_group }}'
        name: "{{ function_app_name }}st"
        account_type: Standard_LRS

    - name: Create container based function app
      azure_rm_functionapp:
        resource_group: "{{ resource_group }}"
        name: "{{ function_app_name }}"
        storage_account: "{{ function_app_name }}st"
        plan:
          resource_group: "{{ resource_group }}"
          name: "{{ function_app_name }}plan"
        container_settings:
          name: zikalino/functionapp
        app_settings:
          DOCKER_REGISTRY_SERVER_URL: https://index.docker.io
          WEBSITE_NODE_DEFAULT_VERSION: 10.14.1
          WEBSITES_ENABLE_APP_SERVICE_STORAGE: no
