- name: Determine Network Address of Master HPC Infrastructure Node
  hosts: localhost
  connection: local

  tasks:

    - name: Getting Public IP address of Master HPC Infrastructure Node
      azure_rm_publicipaddress_facts:
        resource_group: "{{ resource_group }}"
        name: "{{ vm_name }}-hpc-pip"
      register: output

    - name: Adding Public IP to Ansible host group
      add_host:
        hostname: "{{ output.ansible_facts.azure_publicipaddresses[0].properties.ipAddress }}"
        groups: masternode

    - name: Setting Public IP variable
      set_fact:
        masternode_ip: "{{ output.ansible_facts.azure_publicipaddresses[0].properties.ipAddress }}"  

- name: Configure Master HPC Infrastructure Node
  hosts: masternode
  remote_user: "{{ admin_username }}"
  become: yes  

  tasks:

    - name: Ensure NFS is installed
      yum: name=nfs-utils state=installed

    - name: Ensure NFS is enabled
      systemd: name=nfs-server enabled=yes

    - name: Ensure NFS is started
      systemd: name=nfs-server state=started
      ignore_errors: yes

    - name: Ensure rpcbind is enabled
      systemd: name=rpcbind enabled=yes

    - name: Ensure rpcbind is started
      systemd: name=rpcbind state=started
      ignore_errors: yes

    - name: Creating Partition for RAID drive on LUN 0
      parted:
        device: /dev/sdc
        number: 1
        state: present
        flags: [ raid ]

    - name: Creating Partition for RAID drive on LUN 1
      parted:
        device: /dev/sdd
        number: 1
        state: present
        flags: [ raid ]

    - name: Creating Partition for RAID drive on LUN 2
      parted:
        device: /dev/sde
        number: 1
        state: present
        flags: [ raid ]

    - name: Creating Partition for RAID drive on LUN 3
      parted:
        device: /dev/sdf
        number: 1
        state: present
        flags: [ raid ]

    - name: Creating Partition for RAID drive on LUN 4
      parted:
        device: /dev/sdg
        number: 1
        state: present
        flags: [ raid ]

    - name: Creating Partition for RAID drive on LUN 5
      parted:
        device: /dev/sdh
        number: 1
        state: present
        flags: [ raid ]

    - name: Creating Partition for RAID drive on LUN 6
      parted:
        device: /dev/sdi
        number: 1
        state: present
        flags: [ raid ]

    - name: Creating Partition for RAID drive on LUN 7
      parted:
        device: /dev/sdj
        number: 1
        state: present
        flags: [ raid ]

    - name: Creating Partition for RAID drive on LUN 8
      parted:
        device: /dev/sdk
        number: 1
        state: present
        flags: [ raid ]

    - name: Creating Partition for RAID drive on LUN 9
      parted:
        device: /dev/sdl
        number: 1
        state: present
        flags: [ raid ]

    - name: Create RAID 0 Array
      command: "mdadm --create /dev/md0 --level=0 --raid-devices=10 /dev/sdc1 /dev/sdd1 /dev/sde1 /dev/sdf1 /dev/sdg1 /dev/sdh1 /dev/sdi1 /dev/sdj1 /dev/sdk1 /dev/sdl1"
      args:
        creates: /dev/md0

    - name: Create an ext4 filesystem on /dev/md0
      filesystem:
        fstype: ext4
        dev: /dev/md0

    - name: Create mdadm.conf
      command: "mdadm --detail --scan >> /etc/mdadm.conf"
      args:
        creates: /etc/mdadm.conf

    - name: Add e-mail contact to mdadm.conf
      lineinfile:
        path: /etc/mdadm.conf
        line: "MAILADDR root@localhost"
        create: no

    - name: Ensure mdmonitor is enabled
      systemd: name=mdmonitor enabled=yes

    - name: Ensure mdmonitor is started
      systemd: name=mdmonitor state=started
      ignore_errors: yes

    - name: Create mount point for RAID 0 Array
      file:
        path: "/share/data"
        state: directory

    - name: Adding RAID 0 Array entry to /etc/fstab
      lineinfile:
        path: /etc/fstab
        line: "/dev/md0    /share/data      ext4      defaults     1 2"
        create: no

    - name: Mount RAID 0 Array at /share/data
      mount:
        path: /share/data
        src: /dev/md0
        fstype: ext4
        state: present




