- name: Generate Disk Image
  hosts: localhost
  connection: local
  vars_files:
    - ./vars-myvars.yml
  roles:
    - { role: azure.azure_preview_modules }

  tasks:
    - name: Stop Mattermost VM as required to generalize
      azure_rm_virtualmachine:
        resource_group: "{{ resource_group }}"
        name: "{{ vm_name }}-mattermost-master"
        generalized: yes

    - name: Create a generalized disk image of the Mattermost VM
      azure_rm_image:
        resource_group: "{{ resource_group }}"
        name: "{{ vm_name }}-mattermost-disk-image"
        source: "{{ vm_name }}-mattermost-master"
