- name: Deploy Mattermost MySQL PaaS Database
  hosts: localhost
  connection: local
  vars_files:
    - ./vars-myvars.yml
  roles:
    - { role: azure.azure_preview_modules }

  tasks:
  - name: Create MySQL Server for Mattermost Database
    azure_rm_mysqlserver:
      resource_group: "{{ resource_group }}"
      name: "{{ vm_name }}-mattermost-mysql-{{ rnum }}"
      sku:
        name: B_Gen5_1
        tier: Basic
      enforce_ssl: False
      admin_username: "{{ mysql_username }}"
      admin_password: "{{ mysql_password }}"
      storage_mb: 51200

  - name: Create instance of MySQL Database
    azure_rm_mysqldatabase:
      resource_group: "{{ resource_group }}"
      server_name: "{{ vm_name }}-mattermost-mysql-{{ rnum }}"
      name: "{{ mysql_database_name }}"

  - name: Getting Public IP address of the application VM
    azure_rm_publicipaddress_facts:
      resource_group: "{{ resource_group }}"
      name: "{{ vm_name }}-mattermost-master-pip-{{ rnum }}"
    register: output

  - name: Update Firewall Rules using Azure REST API
    azure_rm_resource:
      api_version: '2017-12-01'
      resource_group: "{{ resource_group }}"
      provider: dbformysql
      resource_type: servers
      resource_name: "{{ vm_name }}-mattermost-mysql-{{ rnum }}"
      subresource:
        - type: firewallrules
          name: mattermost
      body:
        properties: 
          startIpAddress: "{{ output.ansible_facts.azure_publicipaddresses[0].properties.ipAddress }}"
          endIpAddress: "{{ output.ansible_facts.azure_publicipaddresses[0].properties.ipAddress }}"
