- name: Create App Service Plan to modernize TODO Application
  hosts: localhost
  connection: local
  vars_files:
    - ./vars-myvars.yml
  roles:
    - { role: azure.azure_preview_modules }

  tasks:

    - name: Create an Azure App Service Plan for TODO Application
      azure_rm_appserviceplan:
        name: "{{ vm_name }}-appservice-plan"
        is_linux: true
        number_of_workers: 1
        resource_group: "{{ resource_group }}"
        sku: S1
