- name: Create Azure Webapp for TODO Application
  hosts: localhost
  connection: local
  vars_files:
    - ./vars-myvars.yml
  roles:
    - { role: azure.azure_preview_modules }

  tasks:

    - name: Obtain Azure Container Registry Facts
      azure_rm_containerregistry_facts:
        resource_group: "{{ resource_group }}"
        name: "{{ vm_name }}2019acregistry"
        retrieve_credentials: true
      register: acr_output

    - name: Obtain Cosmos DB Facts
      azure_rm_cosmosdbaccount_facts:
        resource_group: "{{ resource_group }}"
        name: "{{ vm_name }}-cosmosdb"
        retrieve_keys: all
        retrieve_connection_strings: yes
      register: cosmos_output

    - name: Create Azure Web App for TODO Application utilizing container pushed to Azure Container Registry
      azure_rm_webapp:
        resource_group: "{{ resource_group }}"
        name: "{{ vm_name }}-todo-webapp"
        plan: "{{ vm_name }}-appservice-plan"
        app_settings:
          MONGO_DBCONNECTION: "{{ cosmos_output.accounts[0].connection_strings.connection_strings[0].connection_string }}"
        container_settings:
          name: ossdemo/nodejs-todo
          registry_server_url: "{{ acr_output.registries[0].login_server }}"
          registry_server_user: "{{ acr_output.registries[0].name }}"
          registry_server_password: "{{ acr_output.registries[0].credentials.password }}"
